-- DDL generated by Postico 1.5.17
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE texters (
    id SERIAL PRIMARY KEY,
    phone text NOT NULL,
    item text NOT NULL,
    item_status boolean NOT NULL,
    created_at timestamp without time zone NOT NULL DEFAULT now()
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX texters_pkey ON texters(id int4_ops);
